export const SAVE_TOKEN = 'SAVE_TOKEN';
export const REQUEST_ERROR='REQUEST_ERROR';
export const SAVE_IMINFO='SAVE_IMINFO';
export const SAVE_ROOMID='SAVE_ROOMID';
export const SAVE_USERINFOR='SAVE_USERINFOR';
export const SAVE_NOWUSERID='SAVE_NOWUSERID';
